package com.mercury.pdf.render;

import com.mercury.pdf.render.model.*;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Demonstration of flexible section-based report generation.
 * Shows how to use the new Section model for creating dynamic reports.
 */
public class FlexibleReportDemo {
    
    public static void main(String[] args) throws IOException {
        System.out.println("=== Flexible PDF Report Generation Demo ===\n");
        
        // Example 1: Using builder pattern with flexible sections
        generateFlexibleReport();
        
        // Example 2: Using legacy structure (backward compatibility)
        generateLegacyReport();
        
        System.out.println("\n✓ Demo completed successfully!");
        System.out.println("Generated PDFs:");
        System.out.println("  - flexible-report-demo.pdf");
        System.out.println("  - legacy-report-demo.pdf");
    }
    
    /**
     * Example 1: Generate a report using the new flexible section structure
     */
    private static void generateFlexibleReport() throws IOException {
        System.out.println("1. Generating flexible structure report...");
        
        // Build report with flexible sections using fluent API
        ReportData report = ReportDataBuilder.create()
            .title("Quarterly Business Report")
            .subtitle("Q4 2024 Performance Analysis")
            .reportDate("2024-12-31")
            .reportNumber("RPT-Q4-2024-001")
            
            // Add Executive Summary section
            .addSection(new Section("Executive Summary")
                .withSubtitle("Key Highlights")
                .addParagraph("The fourth quarter of 2024 showed strong performance across all business units. " +
                    "Revenue exceeded targets by 15%, while operational costs were kept under control.")
                .addParagraph("Key achievements include successful product launches, expansion into new markets, " +
                    "and improved customer satisfaction ratings."))
            
            // Add Financial Overview section with table and chart
            .addSection(new Section("Financial Overview")
                .addTable(createFinancialTable())
                .addChart(createRevenueChart()))
            
            // Add Operational Metrics section
            .addSection(new Section("Operational Metrics")
                .withSubtitle("Performance Indicators")
                .addParagraph("Our operational efficiency continued to improve throughout the quarter.")
                .addTable(createMetricsTable())
                .addChart(createEfficiencyChart()))
            
            // Add Recommendations section
            .addSection(new Section("Strategic Recommendations")
                .withCssClass("keep-together")
                .addParagraph("Based on the analysis, we recommend the following actions for Q1 2025:")
                .withCustomContent("<ul style='line-height: 1.8;'>" +
                    "<li>Continue investment in high-growth product lines</li>" +
                    "<li>Expand sales team in emerging markets</li>" +
                    "<li>Enhance customer service capabilities</li>" +
                    "<li>Implement cost optimization initiatives</li>" +
                    "</ul>"))
            
            .reportNotice("This report contains confidential business information. Internal use only.")
            .metadata("Generated by PDF Render v1.0 | Contact: business-intelligence@example.com")
            .build();
        
        // Generate PDF using flexible template
        ReportService service = new ReportService();
        service.getHtmlRenderer().setDefaultTemplateName("flexible");
        byte[] pdfBytes = service.generatePdf(report);
        
        // Save to file
        try (FileOutputStream fos = new FileOutputStream("flexible-report-demo.pdf")) {
            fos.write(pdfBytes);
        }
        
        System.out.println("  ✓ Generated: flexible-report-demo.pdf (" + pdfBytes.length + " bytes)");
    }
    
    /**
     * Example 2: Generate a report using legacy structure (for backward compatibility)
     */
    private static void generateLegacyReport() throws IOException {
        System.out.println("2. Generating legacy structure report (backward compatibility)...");
        
        ReportData report = new ReportData();
        report.setTitle("Legacy Format Report");
        report.setSubtitle("Testing Backward Compatibility");
        report.setReportDate("2024-12-31");
        report.setReportNumber("RPT-LEGACY-001");
        
        // Add table blocks (Section 1)
        TableBlock block1 = new TableBlock("1.1", "Sales Data", createFinancialTable());
        report.setTableBlocks(Arrays.asList(block1));
        
        // Add analysis paragraphs (Section 2)
        report.setAnalysisParagraphs(Arrays.asList(
            "This demonstrates the legacy report structure.",
            "All existing code will continue to work without modifications."
        ));
        
        // Add summary table and charts (Section 3)
        report.setSummaryTable(createMetricsTable());
        report.setCharts(Arrays.asList(createRevenueChart()));
        
        // Add notice (Section 4)
        report.setReportNotice("Legacy format notice");
        report.setMetadata("Legacy metadata");
        
        // Generate PDF using default template (supports both structures)
        ReportService service = new ReportService();
        byte[] pdfBytes = service.generatePdf(report);
        
        // Save to file
        try (FileOutputStream fos = new FileOutputStream("legacy-report-demo.pdf")) {
            fos.write(pdfBytes);
        }
        
        System.out.println("  ✓ Generated: legacy-report-demo.pdf (" + pdfBytes.length + " bytes)");
    }
    
    // Helper methods to create sample data
    
    private static TableData createFinancialTable() {
        return new TableData(
            Arrays.asList("Quarter", "Revenue", "Expenses", "Profit", "Growth"),
            Arrays.asList(
                Arrays.asList("Q1", "$1,200,000", "$800,000", "$400,000", "12%"),
                Arrays.asList("Q2", "$1,350,000", "$850,000", "$500,000", "15%"),
                Arrays.asList("Q3", "$1,450,000", "$900,000", "$550,000", "18%"),
                Arrays.asList("Q4", "$1,600,000", "$950,000", "$650,000", "22%")
            )
        );
    }
    
    private static TableData createMetricsTable() {
        return new TableData(
            Arrays.asList("Metric", "Target", "Actual", "Status"),
            Arrays.asList(
                Arrays.asList("Customer Satisfaction", "85%", "89%", "Exceeded"),
                Arrays.asList("Employee Retention", "90%", "92%", "Exceeded"),
                Arrays.asList("Market Share", "25%", "27%", "Exceeded"),
                Arrays.asList("Product Quality", "95%", "96%", "Met")
            )
        );
    }
    
    private static ChartData createRevenueChart() {
        Map<String, Double> data = new LinkedHashMap<>();
        data.put("Q1", 1200000.0);
        data.put("Q2", 1350000.0);
        data.put("Q3", 1450000.0);
        data.put("Q4", 1600000.0);
        return new ChartData("Quarterly Revenue", "bar", data);
    }
    
    private static ChartData createEfficiencyChart() {
        Map<String, Double> data = new LinkedHashMap<>();
        data.put("Sales", 35.0);
        data.put("Operations", 25.0);
        data.put("Marketing", 20.0);
        data.put("R&D", 15.0);
        data.put("Admin", 5.0);
        return new ChartData("Cost Distribution", "pie", data);
    }
}
